### ISSUE TITLE
JSPB ByteString <-> base64 conversion does not work for negative bytes

### ISSUE THREAD

**Issue by user601239** [google/j2cl-protobuf#2] opened 2020-07-03 06:44 UTC
`bytestring.js` uses `encodeByteArray` of `goog.crypt.base64` which expects numbers in range `0...255`, but Java `byte`s are signed. As a result, the conversion gives wrong output. For example, `ByteString.copyFrom(new byte[] {-1,-1,-1})` serializes to `/` instead of correct `////`.

Similarly, after decoding it's possible to have Java `byte`s with values `128...255`, which is also a bug.

**Comment by gkdn** [comment] 2020-07-07 02:43
Thanks for the feedback.
I'm looking into if the problem is more widespread and touching all unsigned types or more localized to ByteString.

**Comment by gkdn** [comment] 2020-07-22 02:14
There is a problem on unsigneds (https://github.com/google/j2cl-protobuf/commit/bbc38653649c563578bb8a295b5fdf746377a659) but that is ortogonal.

We need to update ByteString to accept/return Int8Array and construct the byte[] from that.

I don't have the bandwidth to fix this at the moment though.

**Comment by gkdn** [comment] 2021-12-02 19:35
This issue should be fixed now.

**Closed as completed by gkdn** 2021-12-02 19:35 UTC
